export const ItemType = {
  // Page: "Page",
  Box: "Box",
  Text: "Text",
  Space: "Space",
  Button: "Button",
  Modal: "Modal",
  Table: "Table",
  TableColumn: "TableColumn",
  Form: "Form",
  FormItem: "FormItem",
  SearchForm: "SearchForm",
  SearchFormItem: "SearchFormItem",
  RemoteComponent: "RemoteComponent",
};
